@ToDo.Api_HostAddress = https://localhost:44303
@TodoController = {{ToDo.Api_HostAddress}}/api/todo


### Get All Todos   
GET {{TodoController}}
Accept: application/json


### Get a Todo Completed Only
GET {{TodoController}}/false
Accept: application/json

### Get a Todo not Completed Only and stautus not-started-yet
GET {{TodoController}}/false/not-started-yet
Accept: application/json

### Get a Todo by ID
GET {{TodoController}}/1
Accept: application/json

### Add a new Todo
POST {{TodoController}}
Accept: application/json
content-type: application/json
{
  "id": 0,
  "title": "Hacer un API de ToDo 2",
  "description": "Hacer un API de ToDo que haga varias cosas, como por ejemplo crear tareas2",
  "isCompleted": false
}

### Update a Todo
PUT {{TodoController}}/1
accept: application/json
content-type: application/json
{
  "id": 1,
  "title": "Completar lista de tareas",
  "description": "Completar lista de tareas usando un API",
  "isCompleted": false
}

### Update a todo status
PUT {{TodoController}}/update-status/1
accept: application/json
content-type: application/json
{
  "status": "Done-but-no-completed"
}

### Delete a Todo
DELETE {{TodoController}}/1
Accept: application/json